// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqopaihguqjdpzzcksge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxb3BhaWhndXFqZHB6emNrc2dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3OTYyNDIsImV4cCI6MjA1NzM3MjI0Mn0.BIjYf6nEaU19krOblDVznrh7x0SIzWc0Fqc0VEumq4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);